### ISSUE TITLE
Create Bus routes

### ISSUE THREAD

**Issue by No-bodyq** [No-bodyq/BRT-System#6]
We should have routes to add a new bus to the system, get bus details, get all buses assigned to a route, Update bus details, Remove a boss from the system

It will probably follow this pattern:
POST /buses - Add a new bus to the system
GET /buses/:busId - Get bus details
GET /buses/route/:routeId - Get all buses assigned to a route
PUT /buses/:busId - Update bus details
DELETE /buses/:busId - Remove a bus from the system

Make sure it queries the db correctly and all code works

**Comment by harrysese** [comment]
I want to do this

**Comment by No-bodyq** [comment]
Assigned @harrysese
